### ISSUE TITLE
diginetica 运行错误

### ISSUE THREAD

**Issue by ABCDRhdjk** [johnny12150/GCE-GNN#1]
在使用diginetica进行训练时，出现了以下问题：
1.process文件处理后节点的数量是43098，但代码里是43040，这里我不清楚有何影响
2.在修改为43098后，进行运行，训练阶段无问题，正常输出损失和正确率，在预测时却出现了
<img width="834" alt="截屏2020-11-05 下午3 25 07" src="https://user-images.githubusercontent.com/32755108/98210528-ab481b00-1f7b-11eb-8c46-4ce6d7a85b24.png">

值得注意的是，在进行yoochoose数据集时却没有这个问题，代码能够正常输出训练和测试，希望能够得到解答。

**Comment by johnny12150** [comment]
Can you check your max node id in testing set while using diginetica for me?

**Comment by ABCDRhdjk** [comment]
node id 具体指的是？

**Comment by ABCDRhdjk** [comment]
我在测试阶段，输出每一批数据的最大节点的id

<img width="654" alt="截屏2020-11-05 下午3 52 50" src="https://user-images.githubusercontent.com/32755108/98212840-24953d00-1f7f-11eb-898d-d1a131b14a07.png">


<img width="374" alt="截屏2020-11-05 下午3 49 50" src="https://user-images.githubusercontent.com/32755108/98212522-adf83f80-1f7e-11eb-929c-b7e9b54626c5.png">

**Comment by johnny12150** [comment]
For the preprocessing part, you should first run the `preprocess.py` and then run the `build_global_graph.py`. This should give you the correct number of nodes/ items among the `main.py`.

**Comment by chungdz** [comment]
@ABCDRhdjk 遇到了同样的问题，请问解决了吗

**Comment by johnny12150** [comment]
> @ABCDRhdjk 遇到了同样的问题，请问解决了吗

After running `preprocess.py` and `build_global_graph.py`, you still face the same issue?

**Comment by chungdz** [comment]
> > @ABCDRhdjk 遇到了同样的问题，请问解决了吗
> 
> After running `preprocess.py` and `build_global_graph.py`, you still face the same issue?

Yeah. However I use the try/except form to skip the problematic batch when testing and it works.

**Comment by johnny12150** [comment]
Ok. I will check it again.
Last time I checked the number of nodes/ items matched in train and test.

**Comment by chungdz** [comment]
I believe the problem is in the NeighborSampler, the subclass of the pytorch Dataloader. It may be caused by the run time environment since I use the recent pytorch version and pytorch_geometric version. As a result you may not find the same error as we are.
![image](https://user-images.githubusercontent.com/24776624/103257409-13d7d500-49cc-11eb-8bae-a86beead3fde.png)

**Comment by johnny12150** [comment]
Now, you can use the code from the original author.
https://github.com/CCIIPLab/GCE-GNN
