### ISSUE TITLE
global-based graph

### ISSUE THREAD

**Issue by ucasiggcas** [johnny12150/GCE-GNN#3]
hi，dear
大佬，这个右边的图咋理解啊？怎么得到的v1的neighbor set是{v2,v3,v5}下面的neighbor set都不理解
![image](https://user-images.githubusercontent.com/35590066/98375814-9e135500-207d-11eb-8ce5-431648a0dc9b.png)
多谢

**Comment by ucasiggcas** [comment]
左下方箭头所指的，如果展示的只是v2的邻集，那么v1怎么会和v2直接相连呢？还有v5

**Comment by johnny12150** [comment]
The figure in the left corner shows that the unique 2-hop neighbors of node 2 which includes v1, v3, v6 in session 1 and v5, v7 insession 2.

**Comment by johnny12150** [comment]
> hi，dear
> 大佬，这个右边的图咋理解啊？怎么得到的v1的neighbor set是{v2,v3,v5}下面的neighbor set都不理解
> ![image](https://user-images.githubusercontent.com/35590066/98375814-9e135500-207d-11eb-8ce5-431648a0dc9b.png)
> 多谢

I am pretty sure the part of v1: {v2, v3, v5} should be v1: {v2, v3, v4}.
If you take a look at the figure in the bottom right, I think the v5 is just a typo.
