### ISSUE TITLE
论文问题

### ISSUE THREAD

**Issue by SiriusXT** [johnny12150/GCE-GNN#6]
想问一下，对于论文中图2b右图邻居集有错误？v1的邻居集应该是v1:{v2,v3,v4}, v7:{v2,v3,v6,v8}

**Comment by johnny12150** [comment]
Let's right!
For more detail, you can view [this](https://github.com/johnny12150/GCE-GNN/issues/3#issuecomment-723940320).

**Comment by SiriusXT** [comment]
> 
> 
> Let's right!
> For more detail, you can view [this](https://github.com/johnny12150/GCE-GNN/issues/3#issuecomment-723940320).

不胜感激，另外尴尬的是Let's right!的意思是论文是对的还是提问是对的，v7对应的是{v2,v3,v6,v8}吗

**Comment by johnny12150** [comment]
Yes, I mean your discovery is right.
> v1:{v2,v3,v4}, v7:{v2,v3,v6,v8}

Since I am not the original author of this paper, this is my assumption and discussion with others.
