### ISSUE TITLE
结果问题

### ISSUE THREAD

**Issue by zd99921** [johnny12150/GCE-GNN#9]
请问为什么这个运行完得到的结果要比原论文的hit和mrr低，是因为hit和mrr的计算方法不同？如果是的话，该怎么改成原论文一致的计算方法？

**Comment by johnny12150** [comment]
Which version of the PyG that you used?
The performance is mainly dependent on the l2 norm over item and session embedding.
I didn't rewrite the GAT as the paper described, so the performance may be a little diverse.

**Comment by zd99921** [comment]
cu110&nbsp;torch-1.7.0 version




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jain Wun ***@***.***&gt;; 
发送时间: 2021年3月13日(星期六) 晚上6:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [johnny12150/GCE-GNN] 结果问题 (#9)





 
Which version of the PyG that you used?

**Comment by johnny12150** [comment]
I think you should try to add session and item l2 norm.
You can see my other repo.
> https://github.com/johnny12150/NISER

The performance gap is quite large when I remove the l2 norm.
However, the original paper didn't mention this technique.

**Comment by zd99921** [comment]
Thanks

**Comment by johnny12150** [comment]
@zd99921 You can try the version from the paper author.
https://github.com/CCIIPLab/GCE-GNN
The result was close to the number they claimed in the paper.
